name: CI
on: [push,pull_request]
jobs:
  lint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: Mushus/golangci-linter@v1

      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0

  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Checkout
        uses: actions/checkout@v2

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Go build
        run: go build -buildmode=plugin -trimpath -o ./hyperbench.so
